name: CI
on:
  push:
    branches:
      - '*'
jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          yarn test:cov
