name: CI
on:
  push:
    branches:
      - '*'
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node modules
        run: |
          yarn

      - name: Test
        run: |
          yarn test:cov

      - name: Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          ./node_modules/.bin/codecov --token=$CODECOV_TOKEN
